apiVersion: operator.run.cloud.google.com/v1alpha1
kind: CloudRun
metadata:
  name: cloud-run
  annotations:
    configmanagement.gke.io/cluster-selector: selector-plat-vmware
spec:
  metricscollector:
    stackdriver:
      projectid: arctiq-anthos
      gcpzone: northamerica-northeast1
      clustername: arctiqchris-homelab-uc1
      secretname: cloudrun-metrics-gsa
      secretkey: key.json
